### ISSUE TITLE
Properly handle usernames with periods

### ISSUE THREAD

**Issue by samuelcouch** [tudev/owlbot#2]
Right now, if Owlbot welcomes a user with a period in the username, it doesn't escape properly `Welcome <@U0AL1765|user.name>` is what gets displayed. 

A good place to start would be [buildUser(username)](https://github.com/tudev/owlbot/blob/master/scripts/welcome.js#L19) as well as the portion of code where a new users is [pushed into the welcome queue](https://github.com/tudev/owlbot/blob/master/scripts/welcome.js#L52).

**Comment by danielkorczak** [comment]
**For reference**
Current: 

> "Welcome <@U0AL1P6BS|lida.lech>! Working on anything interesting?"

Desired: 

> "Welcome @tuf65985! Working on anything interesting?"

**Comment by samuelcouch** [comment]
Steps to resolve this and make [welcome.js](https://github.com/tudev/owlbot/blob/master/scripts/welcome.js) work better. 
1. [buildUser(user)](https://github.com/tudev/owlbot/blob/master/scripts/welcome.js#L20): `return '<@' + user.id + '|' + user.name + '>'` can just be `return '<@' + user.id + '>'` Because of this change, the data that we store in [addUser(user)](https://github.com/tudev/owlbot/blob/master/scripts/welcome.js#L49) can be simplified to remove the `name`key
