### ISSUE TITLE
Fix welcome scheduling

### ISSUE THREAD

**Issue by samuelcouch** [tudev/owlbot#5]
To avoid spamming welcome messages when a single person joins chat, the idea solution is to have a queue that fires off welcome messages on a given interval. That's what [this does](https://github.com/tudev/owlbot/blob/master/scripts/welcome.js#L15)

Although it's not firing every 10 minutes as expected, seems be going once per minute.

**Comment by samuelcouch** [comment]
change the existing `welcomeSchedule` with

``` javascript
  var rule = new schedule.RecurrenceRule()
  rule.minute = new schedule.Range(0, 59, 10)
  var welcomeSchedule = scheduler.scheduleJob(rule, function() {
      welcomeUsers()
  });
```

**Comment by YurkaninRyan** [comment]
https://github.com/tudev/owlbot/pull/6

Potential Fix
